### ISSUE TITLE
Combine Seed and Plant Data Structures

### ISSUE THREAD

**Issue by gracefeng05** [ucsb-cs184-f24/team06#64]
Plants can have a seed property.

**Comment by epuzio** [comment]
Acceptance Criteria:
- Plant and Item data structures inherit from a Seed class
- All extraneous functions and fields are removed from Item and Plant data structures (for example, a Plant object should not have its own getType function, it should inherit this function from the Seed class)
- The shop logic works properly with the new Item class (all preexisting logic should still work with the new data structure)
- The garden plot logic works properly with the new Seed and Plant class
